#!/usr/bin/python3

def List(list):
    for i in range(len(list)):
        print(list[i])


fruits = ["mango", "pineapple", "banana"]   # array of strings
cars = ["ferrari", "mercedes", "toyota"]  # array of strings

List(cars)
List(fruits)
